volumes:
  poptape_fotos:
    name: poptape_fotos

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: poptape/fotos/api:v0.1
    ports:
      - "1236:8002"
    restart: always
    depends_on:
      - mongodb
    volumes:
      - ${LOCAL_LOG_LOC}:/fotos/log
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"
    networks:
      - poptape
  mongodb:
    image: mongo
    restart: always
    ports:
      - "1237:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes: 
      - poptape_fotos:/data/db
    networks:
      - poptape
networks:
  poptape:
    external: true
