version: '3'
services:
  api:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    image: poptape/fotos/api:v0.1
    ports:
      - 1236:8002
    restart: always
    depends_on:
      - mongo_db
    volumes:
      - /var/log:/fotos/log
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"
    networks:
      - net_poptape 
  mongo_db:
    image: poptape/fotos/mongo:v0.1
    restart: always
    env_file: .env
    ports:
      - 1237:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME} 
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes: 
      - poptape_fotos:/data/db
    networks:
      - net_poptape    
networks:
  net_poptape:
    external: true
volumes:
  poptape_fotos:
