version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: poptape/fotos/api:v0.1
    ports:
      - 1236:8002
    restart: always
    depends_on:
      - mongo-db
    volumes:
      - ${LOGFILE}
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"
    networks:
      - net_poptape
  mongo-db:
    image: mongo:3.6
    restart: always
    ports:
      - 1237:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes: 
      - poptape_fotos:/data/db
    networks:
      - net_poptape    
networks:
  net_poptape:
    external: true
volumes:
  poptape_fotos:
