services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: poptape/fotos/api:v${VERSION}
    ports:
      - "1236:8002"
    restart: no
    depends_on:
      - mongodb
    volumes:
      - ${LOCAL_LOG_LOC}:/fotos/log
    logging:
      driver: "json-file"
      options:
        max-size: "10Mb"
        max-file: "5"
    networks:
      - poptape
  mongodb:
    image: mongo:latest
    restart: always
    command:
      - --storageEngine
      - wiredTiger
      - --auth
    ports:
      - "1237:27017"
    volumes:
      - poptape_fotos:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    env_file:
      - path: app/.env
    networks:
      - poptape
volumes:
  poptape_fotos:
    name: poptape_fotos_data
networks:
  poptape:
    external: true
