name: Run unit tests
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
  - cron: '10 10 * * 1' # run "At 10:00 on Monday"

jobs:
  # Run code tests before building the image, to ensure it is good to go
  unit-tests:
    name: Run code tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9] # Using a list so it's extensible for future use
    services:
      mongodb:
        image: mongo:7.0
        ports:
          - 27017:27017
    steps:

      - uses: actions/checkout@v4
      - name: Setting up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # have to create an .env file to be able to run unit tests
      - name: Create .env file from github secrets
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
          
